from __future__ import annotations

import nestpy_microservices
from nestpy_microservices import (
    MicroservicesError,
    OptionalDependencyError,
    PublicRpcError,
    UnknownServiceError,
)


def test_root_facade_is_exact_and_typed() -> None:
    assert set(nestpy_microservices.__all__) == {
        "EventIdentity",
        "EventEnvelope",
        "EventDispatcher",
        "IdentityValidationError",
        "Context",
        "EventDispatchMode",
        "EventContext",
        "EventHandlerMetadata",
        "EventHandlerPlan",
        "EncodedDelivery",
        "ClientTransport",
        "ClientTransportFactory",
        "ClientClusterRoot",
        "ClientsModule",
        "ServiceCluster",
        "ServiceClusterOptions",
        "ServiceProxy",
        "DeliveryDispatcher",
        "HandlerCompilationError",
        "DuplicateSettlementError",
        "EventSubscription",
        "KeyedTransportFactoryReference",
        "InMemoryBroker",
        "InMemoryClientTransport",
        "InMemoryServerTransport",
        "Header",
        "Headers",
        "Inject",
        "InvocationCompletion",
        "MessageCodec",
        "MessageAuthorizationError",
        "MessageConfigurationError",
        "MessageContext",
        "MessageInvocation",
        "MessageInvocationError",
        "MessagePipelineExecutor",
        "MicroservicesModule",
        "MicroservicesOptions",
        "MicroservicesRoot",
        "MessageLimits",
        "MessageMetadata",
        "MessageParameterPlan",
        "MessageRejectedError",
        "MessageRetryableError",
        "MicroservicesError",
        "MsgspecJsonMessageCodec",
        "OptionalDependencyError",
        "PublicRpcError",
        "RemoteRpcError",
        "RpcClientError",
        "RpcOutcomeUnknownError",
        "RpcProtocolError",
        "RpcTimeoutError",
        "UnknownServiceError",
        "Payload",
        "PipelinePlan",
        "ReplyRoute",
        "RemoteRpcErrorData",
        "RESULT_MISSING",
        "RpcHandlerPlan",
        "RpcMetadata",
        "RpcContext",
        "RpcRequestEnvelope",
        "RpcResponseEnvelope",
        "RpcTarget",
        "ServiceIdentity",
        "ServiceHandlerRegistry",
        "ServerTransportFactory",
        "ServiceRuntime",
        "SettlementRecommendation",
        "Publication",
        "PublicationReceipt",
        "ReplyProtocolFailure",
        "ServerTransport",
        "TransportCapacityError",
        "TransportCorrelationError",
        "TransportError",
        "TransportIndeterminateError",
        "TransportRejectedError",
        "TransportStateError",
        "TransportStatus",
        "TransportStatusEvent",
        "TransportTimeoutError",
        "TransportUnavailableError",
        "TransportUnroutableError",
        "RabbitMqModule",
        "RabbitMqChannelRole",
        "RabbitMqConnectionManager",
        "RabbitMqConnectionError",
        "RabbitMqClientTransport",
        "RabbitMqClientTransportFactory",
        "RabbitMqDeliveryMetadata",
        "RabbitMqError",
        "RabbitMqPublisher",
        "RabbitMqServerTransport",
        "RabbitMqServerTransportFactory",
        "BindingDeclaration",
        "ExchangeDeclaration",
        "RabbitMqOptions",
        "RabbitMqRoot",
        "RabbitMqTopology",
        "RabbitMqTransport",
        "RabbitMqStatus",
        "RabbitMqTopologyError",
        "QueueDeclaration",
        "rabbitmq_client_factory_token",
        "rabbitmq_manager_token",
        "rabbitmq_root_token",
        "rabbitmq_server_factory_token",
        "WireDeadlineError",
        "WireDecodingError",
        "WireEncodingError",
        "WireSizeLimitError",
        "WireValidationError",
        "require_future_deadline",
        "require_uuid",
        "require_utc",
        "utc_now",
        "validate_alias",
        "validate_version",
        "compile_controller_message_handlers",
        "compile_discovered_service_handlers",
        "compile_service_handler_registry",
        "CallHeaders",
        "CallTimeout",
        "CausationId",
        "CorrelationId",
        "ProtocolServiceProxy",
        "RpcCallMetadata",
        "RpcCallPlan",
        "ServiceContractMetadata",
        "ServiceContractPlan",
        "compile_service_contract",
        "create_service_proxy",
        "event_handler",
        "get_rpc_call_metadata",
        "get_service_contract_metadata",
        "rpc",
        "rpc_call",
        "service_contract",
    }
    assert all(
        hasattr(nestpy_microservices, name) for name in nestpy_microservices.__all__
    )
    assert issubclass(OptionalDependencyError, MicroservicesError)
    assert issubclass(PublicRpcError, MicroservicesError)
    assert issubclass(UnknownServiceError, MicroservicesError)
    assert MicroservicesError.diagnostic_code == "microservices.error"
    assert (
        OptionalDependencyError("aio-pika", "rabbitmq").diagnostic_code
        == "microservices.optional_dependency"
    )


def test_rabbitmq_facade_is_lazy() -> None:
    import nestpy_microservices.rabbitmq as rabbitmq

    assert set(rabbitmq.__all__) == {
        "BindingDeclaration",
        "ExchangeDeclaration",
        "QueueDeclaration",
        "RabbitMqChannelRole",
        "RabbitMqChannels",
        "RabbitMqClientTransport",
        "RabbitMqClientTransportFactory",
        "RabbitMqConnectionError",
        "RabbitMqConnectionManager",
        "RabbitMqDeliveryMetadata",
        "RabbitMqError",
        "RabbitMqModule",
        "RabbitMqOptions",
        "RabbitMqPublisher",
        "RabbitMqRoot",
        "RabbitMqServerTransport",
        "RabbitMqServerTransportFactory",
        "RabbitMqStatus",
        "RabbitMqTopology",
        "RabbitMqTopologyError",
        "RabbitMqTransport",
        "compile_event_topology",
        "compile_reply_topology",
        "compile_rpc_topology",
        "event_exchange_topology",
        "merge_topologies",
        "rabbitmq_client_factory_token",
        "rabbitmq_manager_token",
        "rabbitmq_root_token",
        "rabbitmq_server_factory_token",
        "require_aio_pika",
    }
    assert issubclass(rabbitmq.RabbitMqConnectionError, rabbitmq.RabbitMqError)
    assert issubclass(rabbitmq.RabbitMqTopologyError, rabbitmq.RabbitMqError)
