"""Portable contracts and reference implementation for persistent streams."""

from tori_py_persistent_streams_core.checkpoints import (
    CheckpointStrategy,
    ExternalCheckpointStrategy,
    InMemoryCheckpointStore,
)
from tori_py_persistent_streams_core.consumers import ConsumerRunner
from tori_py_persistent_streams_core.errors import (
    AdapterContractError,
    CheckpointError,
    CheckpointPersistenceError,
    CheckpointStrategyError,
    IncompatibleStreamError,
    InvalidPartitionError,
    LifecycleError,
    OwnershipError,
    PersistentStreamsError,
    PoisonRecordError,
    PublishingConflictError,
    ResourceLimitError,
    RetentionGapError,
    StalePublishingIdError,
    UnknownStreamError,
    ValidationError,
)
from tori_py_persistent_streams_core.inmemory import InMemoryPersistentLog
from tori_py_persistent_streams_core.models import (
    AppendRequest,
    AvailableBounds,
    Beginning,
    CheckpointKey,
    CursorKind,
    End,
    ExactOffset,
    OwnershipToken,
    PublishOutcome,
    PublishReceipt,
    RecordPage,
    RelativeTime,
    ResumeCursor,
    StartModeCapabilities,
    StartPosition,
    StoredRecord,
    StreamDefinition,
    StreamLimits,
    Subscription,
    Timestamp,
)
from tori_py_persistent_streams_core.protocols import (
    CheckpointStore,
    PartitionLease,
    PersistentLog,
    PersistentStreamAdapter,
    RecordHandler,
)
from tori_py_persistent_streams_core.routing import (
    DEFAULT_PARTITION_ROUTER,
    PartitionRouter,
    Sha256PartitionRouter,
)

__all__ = [
    "AdapterContractError",
    "AppendRequest",
    "AvailableBounds",
    "Beginning",
    "CheckpointError",
    "CheckpointKey",
    "CheckpointPersistenceError",
    "CheckpointStore",
    "CheckpointStrategy",
    "CheckpointStrategyError",
    "ConsumerRunner",
    "CursorKind",
    "DEFAULT_PARTITION_ROUTER",
    "End",
    "ExactOffset",
    "ExternalCheckpointStrategy",
    "InMemoryCheckpointStore",
    "InMemoryPersistentLog",
    "IncompatibleStreamError",
    "InvalidPartitionError",
    "LifecycleError",
    "OwnershipError",
    "OwnershipToken",
    "PartitionLease",
    "PartitionRouter",
    "PersistentLog",
    "PersistentStreamAdapter",
    "PersistentStreamsError",
    "PoisonRecordError",
    "PublishOutcome",
    "PublishReceipt",
    "PublishingConflictError",
    "RecordHandler",
    "RecordPage",
    "RelativeTime",
    "ResourceLimitError",
    "ResumeCursor",
    "RetentionGapError",
    "Sha256PartitionRouter",
    "StalePublishingIdError",
    "StartPosition",
    "StartModeCapabilities",
    "StoredRecord",
    "StreamDefinition",
    "StreamLimits",
    "Subscription",
    "Timestamp",
    "UnknownStreamError",
    "ValidationError",
]
