"""Framework-agnostic CQRS primitives."""

from tori_py_cqrs_core.builder import CqrsBuilder, CqrsBuses
from tori_py_cqrs_core.buses import (
    CommandBus,
    EventBus,
    EventErrorHandler,
    EventHandlerFailure,
    QueryBus,
)
from tori_py_cqrs_core.context import BusHandles, HandlerContext
from tori_py_cqrs_core.envelope import (
    DeliveryMetadata,
    DeliveryReceipt,
    Envelope,
    ReplyEnvelope,
)
from tori_py_cqrs_core.errors import (
    CqrsError,
    CqrsValidationError,
    DuplicateCommandHandlerError,
    DuplicateHandlerError,
    DuplicateQueryHandlerError,
    EnvelopeValidationError,
    InvalidHandlerRegistrationError,
    InvalidLifecycleTransitionError,
    InvalidReplyCorrelationError,
    InvalidTransportReplyError,
    MissingHandlerError,
    NestedCommandDispatchError,
    QueueCapacityError,
    RequestTimeoutError,
    TransportLifecycleError,
    TransportNotStartedError,
    TransportStoppedError,
)
from tori_py_cqrs_core.identity import message_type_for
from tori_py_cqrs_core.inmemory import InMemoryTransport, TransportState
from tori_py_cqrs_core.messages import Command, Event, Message, Query
from tori_py_cqrs_core.protocols import (
    AsyncMessageHandler,
    CommandBusHandle,
    DispatchContext,
    EventBusHandle,
    FunctionHandlerContext,
    HandlerFunction,
    HandlerProvider,
    HandlerRegistration,
    QueryBusHandle,
    Transport,
    TransportConsumer,
)
from tori_py_cqrs_core.provider import DefaultHandlerProvider
from tori_py_cqrs_core.registrations import (
    CommandHandler,
    EventsHandler,
    HandlerKind,
    HandlerMetadata,
    HandlerStyle,
    QueryHandler,
    RegisteredHandler,
    TargetMode,
    get_handler_metadata,
    handles,
)
from tori_py_cqrs_core.registry import HandlerRegistry

__all__ = [
    "AsyncMessageHandler",
    "BusHandles",
    "Command",
    "CommandBus",
    "CommandBusHandle",
    "CommandHandler",
    "CqrsError",
    "CqrsBuilder",
    "CqrsBuses",
    "CqrsValidationError",
    "DeliveryMetadata",
    "DeliveryReceipt",
    "DispatchContext",
    "DuplicateCommandHandlerError",
    "DuplicateHandlerError",
    "DuplicateQueryHandlerError",
    "Envelope",
    "EnvelopeValidationError",
    "Event",
    "EventBus",
    "EventErrorHandler",
    "EventHandlerFailure",
    "EventBusHandle",
    "EventsHandler",
    "DefaultHandlerProvider",
    "HandlerFunction",
    "HandlerContext",
    "FunctionHandlerContext",
    "HandlerKind",
    "HandlerMetadata",
    "HandlerProvider",
    "HandlerRegistration",
    "HandlerRegistry",
    "HandlerStyle",
    "InvalidHandlerRegistrationError",
    "InvalidLifecycleTransitionError",
    "InvalidReplyCorrelationError",
    "InvalidTransportReplyError",
    "InMemoryTransport",
    "Message",
    "MissingHandlerError",
    "NestedCommandDispatchError",
    "Query",
    "QueryBus",
    "QueryBusHandle",
    "QueryHandler",
    "QueueCapacityError",
    "ReplyEnvelope",
    "RequestTimeoutError",
    "RegisteredHandler",
    "TargetMode",
    "Transport",
    "TransportConsumer",
    "TransportLifecycleError",
    "TransportNotStartedError",
    "TransportStoppedError",
    "TransportState",
    "get_handler_metadata",
    "handles",
    "message_type_for",
]
